### ISSUE TITLE
internal server error

### ISSUE THREAD

**Issue by bimaarif** [sejator/posci4#1]
ketika melakukan login muncul bug internal server error.

**Comment by sejator** [comment]
bisa di sertakan untuk error lognya apa?

**Comment by bimaarif** [comment]
![error1](https://github.com/sejator/posci4/assets/39897330/ddde7cf5-22d9-44bb-a8be-88bf9b1e3e45)
![error2](https://github.com/sejator/posci4/assets/39897330/487cdc90-2e12-416f-866b-31c601aa7547)

errornya ketika melakukan login.

**Comment by bimaarif** [comment]
saya pakai PHP versi 8.1

**Comment by sejator** [comment]
Maaf untuk project ini masih menggunakan versi php 7.4, belum di tes untuk versi 8 atau lebih.

**Comment by sejator** [comment]
Belum sempat mau upgrade, ini ada issue juga masalah keamanan di core ci untuk versi yang di pakai.

**Comment by bimaarif** [comment]
ok, terima kasih informasinya

**Comment by sejator** [comment]
Sama-sama...
